/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // Plugin de Spring Boot
    id("org.springframework.boot") version "3.3.0"
    // Administrador de dependencias de Spring (maneja las versiones de los starters de forma automática)
    id("io.spring.dependency-management") version "1.1.5"
}

group = "org.example"
version = "0.0.1-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // El "starter" base para aplicaciones Spring Boot
    implementation("org.springframework.boot:spring-boot-starter")
    
    // OPCIONAL: Descomenta esta línea si vas a crear una API Web / REST
    implementation("org.springframework.boot:spring-boot-starter-web")
    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

springBoot {
    mainClass.set("org.example.Application")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.Application"
}


