services:
  transporte:
    build: .
    container_name: lab09-transporte
    ports:
      - "8084:8084"
    environment:
      PORT: 8084
      NODE_ENV: development
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    restart: unless-stopped