// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: converter.proto

package com.mycompany.converter;

public interface ConvertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConvertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double result = 1;</code>
   * @return The result.
   */
  double getResult();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>bool success = 3;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string errorMessage = 4;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 4;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
