// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: converter.proto

package com.mycompany.converter;

public interface ConvertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConvertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>double value = 2;</code>
   * @return The value.
   */
  double getValue();
}
