// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: converter.proto

package com.mycompany.converter;

public final class ConverterProto {
  private ConverterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConvertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConvertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConvertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConvertResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017converter.proto\"-\n\016ConvertRequest\022\014\n\004t" +
      "ype\030\001 \001(\t\022\r\n\005value\030\002 \001(\001\"]\n\017ConvertRespo" +
      "nse\022\016\n\006result\030\001 \001(\001\022\023\n\013description\030\002 \001(\t" +
      "\022\017\n\007success\030\003 \001(\010\022\024\n\014errorMessage\030\004 \001(\t2" +
      "9\n\tConverter\022,\n\007Convert\022\017.ConvertRequest" +
      "\032\020.ConvertResponseB+\n\027com.mycompany.conv" +
      "erterB\016ConverterProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConvertRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConvertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConvertRequest_descriptor,
        new java.lang.String[] { "Type", "Value", });
    internal_static_ConvertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConvertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConvertResponse_descriptor,
        new java.lang.String[] { "Result", "Description", "Success", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
