/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.sun.net.httpserver.Filter;
import com.sun.net.httpserver.HttpContext;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import jakarta.xml.ws.Endpoint;
import java.io.IOException;
import java.net.InetSocketAddress;

public class App {
  
    public static void main(String[] args) throws IOException {
        int puerto = 8080;
        String ruta = "/calculadora";
    
        // Creamos el servidor HTTP manualmente en el puerto 8080
        HttpServer server = HttpServer.create(new InetSocketAddress(puerto), 0);
    
        // Creamos el contexto (la ruta) para el servicio
        HttpContext context = server.createContext(ruta);
    
        // Añadimos el Filtro para interceptar y meter las cabeceras CORS
        context.getFilters().add(new Filter() {
            @Override
            public void doFilter(HttpExchange exchange, Chain chain) throws IOException {
                // Agregamos las cabeceras CORS obligatorias
                exchange.getResponseHeaders().add("Access-Control-Allow-Origin", "*");
                exchange.getResponseHeaders().add("Access-Control-Allow-Methods", "POST, GET, OPTIONS");
                // Es vital incluir 'SOAPAction' ya que los clientes SOAP antiguos/estándar la envían
                exchange.getResponseHeaders().add("Access-Control-Allow-Headers", "Content-Type, Authorization, SOAPAction");

                // El navegador siempre envía un 'OPTIONS' antes de la petición real (Preflight)
                if ("OPTIONS".equalsIgnoreCase(exchange.getRequestMethod())) {
                    // Respondemos inmediatamente con un 204 (No Content) para darle luz verde al navegador
                    exchange.sendResponseHeaders(204, -1);
                    return; 
                }

                // Si no es OPTIONS (es el POST real con el XML), dejamos que continúe hacia el motor de SOAP
                chain.doFilter(exchange);
            }

            @Override
            public String description() {
                return "Filtro para habilitar CORS en SOAP";
            }
        });
    
        System.out.println("Publicando servicio SOAP con CORS habilitado en: http://localhost:" + puerto + ruta);
    
        // Instanciamos el Endpoint y lo asociamos a nuestro contexto HTTP modificado
        Endpoint endpoint = Endpoint.create(new CalculadoraSOAPImpl());
        endpoint.publish(context);
    
        // Encendemos el servidor
        server.start();
    
        System.out.println("Servicio publicado exitosamente.");
        System.out.println("El WSDL está disponible en: http://localhost:" + puerto + ruta + "?wsdl");    
    }
}
