version: '3.8'

services:
  inventario:
    build: .
    container_name: logifresh-inventario
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - REDIS_HOST=redis-inventario
      - REDIS_PORT=6379
    depends_on:
      redis-inventario:
        condition: service_healthy
    networks:
      - logifresh-network

  redis-inventario:
    image: redis:7-alpine
    container_name: logifresh-redis-inventario
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - logifresh-network

networks:
  logifresh-network:
    driver: bridge